-- Baseline: the Supabase (Postgres) production schema as it existed before the
-- hardening migration (0002). Captured from the live project so the schema is
-- recoverable from git, not only from the dashboard. The SQLite mirror lives in
-- lib/db/schema.sql; the RPCs below are the Postgres equivalents the app calls
-- through lib/db/supabase.ts.

-- === Tables ===

CREATE TABLE IF NOT EXISTS public.chunks (
  id text PRIMARY KEY,
  book text NOT NULL,
  page_start integer NOT NULL,
  page_end integer NOT NULL,
  category_hint text NOT NULL,
  text text NOT NULL,
  -- Generated full-text vector + GIN index power search_chunks().
  fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, text)) STORED
);
CREATE INDEX IF NOT EXISTS chunks_fts_idx ON public.chunks USING gin (fts);
CREATE INDEX IF NOT EXISTS chunks_book_idx ON public.chunks USING btree (book);

CREATE TABLE IF NOT EXISTS public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  stem text NOT NULL,
  choices jsonb NOT NULL,
  correct_index integer NOT NULL,
  explanation text,
  source_chunk_id text REFERENCES public.chunks (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.quiz_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.answers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id bigint NOT NULL REFERENCES public.quiz_attempts (id),
  question_id bigint NOT NULL REFERENCES public.questions (id),
  selected_index integer NOT NULL,
  is_correct boolean NOT NULL,
  answered_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session text NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- === RPCs (original versions; superseded by 0002) ===

CREATE OR REPLACE FUNCTION public.search_chunks(q text, k integer)
RETURNS SETOF public.chunks LANGUAGE sql STABLE AS $$
  SELECT c.* FROM public.chunks c
  WHERE c.fts @@ websearch_to_tsquery('english', q)
  ORDER BY ts_rank(c.fts, websearch_to_tsquery('english', q)) DESC
  LIMIT k
$$;

CREATE OR REPLACE FUNCTION public.questions_by_category(cat text, n integer)
RETURNS SETOF public.questions LANGUAGE sql STABLE AS $$
  SELECT * FROM public.questions WHERE category = cat ORDER BY random() LIMIT n
$$;

CREATE OR REPLACE FUNCTION public.get_attempt_score(aid bigint)
RETURNS TABLE(total bigint, correct bigint) LANGUAGE sql STABLE AS $$
  SELECT count(*)::bigint, coalesce(sum(is_correct::int),0)::bigint
  FROM public.answers WHERE attempt_id = aid
$$;

CREATE OR REPLACE FUNCTION public.attempt_stats()
RETURNS TABLE(category text, attempted bigint, correct bigint) LANGUAGE sql STABLE AS $$
  SELECT q.category, count(*)::bigint, coalesce(sum(a.is_correct::int),0)::bigint
  FROM public.answers a JOIN public.questions q ON q.id = a.question_id
  GROUP BY q.category
$$;

CREATE OR REPLACE FUNCTION public.attempt_history()
RETURNS TABLE(attempt_id bigint, completed_at timestamptz, total bigint, correct bigint)
LANGUAGE sql STABLE AS $$
  SELECT qa.id, qa.completed_at, count(a.id)::bigint,
         coalesce(sum(a.is_correct::int),0)::bigint
  FROM public.quiz_attempts qa JOIN public.answers a ON a.attempt_id = qa.id
  GROUP BY qa.id ORDER BY qa.id ASC
$$;

CREATE OR REPLACE FUNCTION public.missed_questions()
RETURNS SETOF public.questions LANGUAGE sql STABLE AS $$
  SELECT DISTINCT q.* FROM public.answers a
  JOIN public.questions q ON q.id = a.question_id
  WHERE a.is_correct = false
$$;

CREATE OR REPLACE FUNCTION public.completed_questions()
RETURNS SETOF public.questions LANGUAGE sql STABLE AS $$
  SELECT DISTINCT q.* FROM public.answers a
  JOIN public.questions q ON q.id = a.question_id
$$;

-- === RLS (original: RLS enabled but anon could do ANYTHING; tightened in 0002) ===

ALTER TABLE public.chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_all_chunks ON public.chunks FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all_questions ON public.questions FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all_attempts ON public.quiz_attempts FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all_answers ON public.answers FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all_chat ON public.chat_messages FOR ALL TO anon USING (true) WITH CHECK (true);
